services:
  void:
    image: hescc/void:latest
    container_name: void
    network_mode: host
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./config:/app/config 
      - /data:/data
